language: node_js

node_js:
  - '10'

cache:
  directories:
    - 'node_modules'

install:
  - npm install

before_script:
  - export THEME='jsonresume-theme-paper'
  - export OUTPUT_PATH=

script:
  - npm run build

notifications:
  email:
    on_failure: always

branches:
  only:
    - master

