language: node_js

node_js:
  - '12'

before_script:
  - export THEME='jsonresume-theme-paper'
  - export OUTPUT_PATH='dist/resume.all'

script:
  - npm run build

notifications:
  email:
    on_failure: always

branches:
  only:
    - master

