language: node_js

node_js:
  - '10'

cache:
  directories:
    - 'node_modules'

env:
  - THEME = 'jsonresume-theme-paper'

install:
  - npm install
  - npm run build

script: echo 'skip test' # Skip `yarn test`

notifications:
  email:
    on_failure: always

branches:
  only:
    - master

