name: resume

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
        THEME: jsonresume-theme-paper
        OUTPUT_PATH: dist/resume.all
